# Generated by Django 4.1.2 on 2022-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingMethodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pricing_method', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('Strategy', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
