# Generated by Django 4.1.2 on 2022-10-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0004_physicalblotter_book_physicalblotter_counter_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblotter',
            name='Strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.strategymodel'),
        ),
    ]
