# Generated by Django 4.1.2 on 2022-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0005_physicalblotter_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblotter',
            name='Derivative',
            field=models.CharField(choices=[('physical', 'physical')], default='physical', max_length=100),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Pricing_Contract',
            field=models.CharField(choices=[('Naphtha FOB Arar', 'Naphtha FOB Arar'), ('ECO-1042/2022', 'ECO-1042/2022'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Product',
            field=models.CharField(choices=[('Fuel Oil', 'Fuel Oil'), ('Naphtha', 'Naphtha'), ('Gasoline Blend sb', 'Gasoline Blend sb')], default='Fuel Oil', max_length=100),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='unit',
            field=models.CharField(choices=[('MT', 'MT'), ('BBL', 'BBL'), ('m³', 'm³')], max_length=100, null=True),
        ),
    ]
