# Generated by Django 4.1.2 on 2022-10-29 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0006_physicalblotter_derivative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblotter',
            name='BL_Date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Density',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Nominated_quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Premium_discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Pricing_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.pricingmethodemodel'),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Pricing_term',
            field=models.CharField(choices=[('Tomorrow', 'Tomorrow'), ('25 days after', '25 days after')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='kMT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='kbbl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='m3',
            field=models.FloatField(null=True),
        ),
    ]
