# Generated by Django 4.1.2 on 2022-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0008_physicalblotter_end_date_physicalblotter_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblotter',
            name='Delivery_mode',
            field=models.CharField(blank=True, choices=[('1', 'Tank'), ('2', 'Vessel'), ('3', 'PLT')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='External_Terminal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Tank_no',
            field=models.CharField(blank=True, choices=[('Tank1', 'Tank1'), ('Tank2', 'Tank2'), ('Tank3', 'Tank3'), ('Tank4', 'Tank4')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Terminal',
            field=models.CharField(choices=[('Terminal1', 'Terminal1'), ('Terminal2', 'Terminal2')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Vessal_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='holidays',
            field=models.CharField(choices=[('singapore_holidays', 'singapore_holidays'), ('plate_holidays', 'plate_holidays')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='port',
            field=models.CharField(choices=[('Port1', 'Port1'), ('Port2', 'Port2')], max_length=120, null=True),
        ),
    ]
