# Generated by Django 4.1.2 on 2022-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0009_physicalblotter_delivery_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalblotter',
            name='Difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Fright_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Heading_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Shore_recieved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Terminal_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='Total_no_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='additional_secondary_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='price_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='price_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='priced_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='total_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='unprice_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='unprice_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicalblotter',
            name='unpriced_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
