# Generated by Django 4.1.2 on 2022-10-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0010_physicalblotter_difference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalblotter',
            name='Heading_text',
        ),
    ]
