# Generated by Django 4.1.2 on 2022-11-04 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0011_remove_physicalblotter_heading_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterPartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter_Party', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singapore_Platts', models.DateField(default=datetime.datetime.now)),
                ('ICE', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PricingContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pricing_Contract', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tradermodel',
            name='Trader',
            field=models.CharField(default='Select', max_length=120),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='Book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.bookmodel'),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='Counter_Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.counterpartymodel'),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='Pricing_Contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.pricingcontractmodel'),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.productmodel'),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.unitmodel'),
        ),
    ]
