# Generated by Django 4.1.2 on 2022-11-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0014_alter_physicalblotter_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalblotter',
            name='price_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='total_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='unprice_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
