# Generated by Django 4.1.2 on 2022-11-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0015_alter_physicalblotter_price_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalblotter',
            name='kMT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='kbbl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalblotter',
            name='m3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
